
    <div class="wrapper">
		<div class="header header-filter" style="background-image: url('./public/img/examples/city.jpg');"></div>
		<div class="main main-raised">
			<div class="profile-content">
	            <div class="container">
	                <div class="row">
	                    <div class="profile">
	                        <div class="avatar">
	                            <img src=<?php echo $singerPhoto; ?> alt="Circle Image" class="img-circle img-responsive img-raised">
	                        </div>
	                        <div class="name">
	                            <h3 class="title"> <?php echo $singerName; ?> </h3>
								<h6> <?php echo $singerTitle; ?> </h6>
	                        </div>
	                    </div>
	                </div>
	                <div class="description text-center">
                        <p>
                        	<?php echo $singerBio; ?>
                        </p>
	                </div>

					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<div class="profile-tabs">
			                    <div class="nav-align-center">
									<ul class="nav nav-pills" role="tablist">
										<li class="active">
											<a href="#studio" role="tab" data-toggle="tab">
												<i class="material-icons">Hot</i>
												Hot Videos
											</a>
										</li>
										<li>
				                            <a href="#work" role="tab" data-toggle="tab">
												<i class="material-icons">All</i>
												All Videos
				                            </a>
				                        </li>
				                       
				                    </ul>

				                    <div class="tab-content gallery">
										<div class="tab-pane active" id="studio">
				                            <div class="row">
												<div class="col-md">

													<?php echo $singerHotVideos; ?>
												</div>
				                            </div>
				                        </div>
				                        <div class="tab-pane text-center" id="work">
											<div class="row">
												<div class="col-2">
													<?php echo $singerAllVideos; ?>
												</div>
											</div>
				                        </div>

				                    </div>
								</div>
							</div>
							<!-- End Profile Tabs -->
						</div>
	                </div>

	            </div>
	        </div>
		</div>

