<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title> YouTube - Redesign</title>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href="./public/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="./public/css/material-kit.css" rel="stylesheet" type="text/css" />

    <style type="text/css">
    .navbar, .navbar.navbar-default {
        background-color: #222222;
        color: #ffffff;
    }

    .avatar {
        text-align: center;
        margin-left: 38%;
    }

    .name {
        text-align: center;
    }

    .tab-content {
        margin-left: -20%;
    }

    .nav-pills > li.active > a, .nav-pills > li.active > a:focus, .nav-pills > li.active > a:hover {
        color: #FFFFFF;
        box-shadow: 0 16px 26px -10px rgba(176, 39, 39, 0.56), 0 4px 25px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(176, 39, 39, 0.2);
    }
</style>

 <link href="./public/css/custom.css" rel="stylesheet" type="text/css" />
</head>

<body>

    <nav class="navbar navbar-transparent navbar-fixed-top navbar-color-on-scroll">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index"><img style="width: 20%" src="./public/img/ylogo.png" /></a>

            </div>
            <div>
                <div class="collapse navbar-collapse" id="navigation-example">
                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a> <?php echo $usergreeting; ?> </a>
                        </li>

                        <li>
                            <?php echo $profileField; ?>
                        </li>

                        
                        <li>
                            <?php echo $logoutField; ?>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


        <?php echo $this->getContent(); ?>

        <!--   Core JS Files   -->
        <script src="./public/js/jquery.min.js" type="text/javascript"></script>
        <script src="./public/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="./public/js/material.min.js"></script>

        <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
        <script src="./public/js/nouislider.min.js" type="text/javascript"></script>

        <!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
        <script src="./public/js/bootstrap-datepicker.js" type="text/javascript"></script>

        <!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
        <script src="./public/js/material-kit.js" type="text/javascript"></script>
    </body>

    <footer class="footer">
        <div class="container">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="http://www.creative-tim.com">
                         Serhan Gürsoy
                     </a>
                 </li>
                 <li>
                    <a href="">
                     About Us
                 </a>
             </li>
             <li>
                <a href="">
                 Blog
             </a>
         </li>
         <li>
            <a href="">
                Licenses
            </a>
        </li>
    </ul>
</nav>
<div class="copyright pull-right">
    &copy; 2017,  by Serhan Gürsoy used Material-Theme
</div>
</div>
</footer>

</html>
