<div class="wrapper">
	<div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">
		<div class="container"  style="padding-top: 10%; padding-bottom: 10%">
			<div class="row" >
				<div class="col-md-6">
					<h1 class="title" style="color:white">Watch. Listen. Enjoy!</h1>
				</div>
			</div>
		</div>
	</div>

	<div class="main main-raised">
		<div class="container">
			<div class="section text-center">
				<h2 class="title">Check the newest artists!</h2>
				<div class="team">
						<?php echo $singerList; ?>
				</div>
			</div>
		</div>
	</div>